from extract import df
import pandas as pd

# Rename columns for better clarity
df.columns = ['risk_value', 'date']

# Convert the 'date' column to datetime format for temporal analysis
df['date'] = pd.to_datetime(df['date'])

# Sort the data by date to ensure chronological order
df = df.sort_values(by='date').reset_index(drop=True)

# Calculate the daily variation in the risk value
df['daily_variation'] = df['risk_value'].diff()

# Add a column to identify the trend: increase, decrease, or no change
df['trend'] = df['daily_variation'].apply(lambda x: 'Increase' if x > 0 else 'Decrease' if x < 0 else 'No Change')

# Remove any null values generated by calculations
df_clean = df.dropna()

# Display the transformed DataFrame
print(df_clean.head())

# Save the transformed DataFrame for the load.py script
df_clean.to_csv("data/transformed_data.csv", index=False)