from extract import df
import pandas as pd

# Read the DataFrame from a file generated by extract.py (optional)

# Rename columns for better clarity
df.columns = ['risk_value', 'date']

# Convert the 'date' column to datetime format for temporal analysis
df['date'] = pd.to_datetime(df['date'])

# Sort the data by date to ensure chronological order
df = df.sort_values(by='date').reset_index(drop=True)

# Calculate the daily variation in the risk value
df['daily_variation'] = df['risk_value'].diff()

# Calculate the percentage change in risk value
df['percent_change'] = df['risk_value'].pct_change() * 100

# Add a column to identify the trend: increase, decrease, or no change
df['trend'] = df['daily_variation'].apply(lambda x: 'Increase' if x > 0 else 'Decrease' if x < 0 else 'No Change')

# Remove any null values generated by calculations
df = df.dropna()

# Display the transformed DataFrame
print(df.head())

# Save the transformed DataFrame for the load.py script
df.to_csv("transformed_data.csv", index=False)
